export const languages = ["Lietuvių", "Anglų"];
export const words = {
  Require: "Reikalauti",
  Communicate: "Bendrauti",
  Solve: "Išspręsti",
  Improve: "Patobulinti",
  Fluently: "Laisvai",
  "Find out": "Sužinoti",
  Refuse: "Atsisakyti",
  Advise: "Patarti",
  Offer: "Pasiūlyti",
  Suggest: "Pasiūlyti",
  Propose: "Pasiūlyti",
  Agreement: "Susitarimas",
  Possibility: "Galimybė",
  Opportunity: "Galimybė",
  Remind: "Priminti",
  Take: "Paimti",
  Listen: "Klausyti",
  Disturb: "Trukdyti",
  Stay: "Pasilikti",
  Remotely: "Per nuotolį",
  Coperate: "Bendradarbiauti",
  Foreign: "Užsienio",
  Deals: "Reikalai",
  Lessons: "Pamokos",
  Expect: "Tikėtis",
  Cost: "Kaina",
  Often: "Dažnai",
  Boil: "Virti",
  Spend: "Praleisti",
  Participate: "Dalyvauti",
  Abroad: "Užsienis",
  Earn: "Užsidirbti",
  Depends: "Priklauso",
  Depend: "Priklausyti",
  Use: "Naudoti",
  For: "Už",
  Enough: "Pakankamai",
  Mean: "Reikšti",
  Do: "Daryti",
  Broken: "Sugedęs",
};
